version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "16:90:f7:c9:62:90:3f:f1:ee:16:6b:4a:5d:eb:58:e2"
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Gatsby build site
          command: yarn build
      - run:
          name: Prepare shell commands
          command: cp .scripts/react-deploy.sh ../ && chmod +x ../react-deploy.sh
      - run:
          name: Run deploy scripts
          command: ../react-deploy.sh
