export const possessionList = [
    {
        symbol: 'BTC',
        coinName: 'Bitcoin',
        ImageUrl: 'btc@2x.png',
        possession: 0.68,
    },
    {
        symbol: 'ETH',
        coinName: 'Ethereum',
        ImageUrl: 'eth@2x.png',
        possession: 0.38,
    },
    {
        symbol: 'XRP',
        coinName: 'Ripple',
        ImageUrl: 'xrp@2x.png',
        possession: 0,
    },
    {
        symbol: 'BCH',
        coinName: 'Bitcoin Cash / BCC',
        ImageUrl: 'bch@2x.png',
        possession: 0,
    },
    {
        symbol: 'ADA',
        coinName: 'Cardano',
        ImageUrl: 'ada@2x.png',
        possession: 0,
    },
    {
        symbol: 'XEM',
        coinName: 'NEM',
        ImageUrl: 'xem@2x.png',
        possession: 0,
    },
    {
        symbol: 'IOTA',
        coinName: 'IOTA',
        ImageUrl: 'miota@2x.png',
        possession: 0,
    },
    {
        symbol: 'EOS',
        coinName: 'EOS',
        ImageUrl: 'eos@2x.png',
        possession: 0,
    },
    {
        symbol: 'DASH',
        coinName: 'DigitalCash',
        ImageUrl: 'dash@2x.png',
        possession: 0,
    },
    {
        symbol: 'NEO',
        coinName: 'NEO',
        ImageUrl: 'neo@2x.png',
        possession: 0,
    },
    {
        symbol: 'TRX',
        coinName: 'Tronix',
        ImageUrl: 'trx@2x.png',
        possession: 0,
    },
    {
        symbol: 'XMR',
        coinName: 'Monero',
        ImageUrl: 'xmr@2x.png',
        possession: 2,
    },
]

export const watchList = [
    {
        symbol: 'BTC',
        coinName: 'Bitcoin',
        ImageUrl: 'btc@2x.png',
    },
    {
        symbol: 'ETH',
        coinName: 'Ethereum',
        ImageUrl: 'eth@2x.png',
    },
    {
        symbol: 'XRP',
        coinName: 'Ripple',
        ImageUrl: 'xrp@2x.png',
    },
    {
        symbol: 'BCH',
        coinName: 'Bitcoin Cash / BCC',
        ImageUrl: 'bch@2x.png',
    },
    {
        symbol: 'ADA',
        coinName: 'Cardano',
        ImageUrl: 'ada@2x.png',
    },
    {
        symbol: 'XEM',
        coinName: 'NEM',
        ImageUrl: 'xem@2x.png',
    },
    {
        symbol: 'IOTA',
        coinName: 'IOTA',
        ImageUrl: 'miota@2x.png',
    },
    {
        symbol: 'EOS',
        coinName: 'EOS',
        ImageUrl: 'eos@2x.png',
    },
    {
        symbol: 'DASH',
        coinName: 'DigitalCash',
        ImageUrl: 'dash@2x.png',
    },
    {
        symbol: 'NEO',
        coinName: 'NEO',
        ImageUrl: 'neo@2x.png',
    },
    {
        symbol: 'TRX',
        coinName: 'Tronix',
        ImageUrl: 'trx@2x.png',
    },
    {
        symbol: 'XMR',
        coinName: 'Monero',
        ImageUrl: 'xmr@2x.png',
    },
]

export const selectList = [
    {
        label: 'Bitcoin',
        value: 'BTC',
    },
    {
        label: 'Ethereum',
        value: 'ETH',
    },
    {
        label: 'Ripple',
        value: 'XRP',
    },
    {
        label: 'Bitcoin Cash',
        value: 'BCH',
    },
    {
        label: 'Cardano',
        value: 'ADA',
    },
    {
        label: 'NEM',
        value: 'XEM',
    },
    {
        label: 'IOTA',
        value: 'IOTA',
    },
    {
        label: 'EOS',
        value: 'EOS',
    },
    {
        label: 'DigitalCash',
        value: 'DASH',
    },
    {
        label: 'NEO',
        value: 'NEO',
    },
    {
        label: 'Tronix',
        value: 'TRX',
    },
    {
        label: 'Monero',
        value: 'XMR',
    },
]

export const legalList = [
    {
        label: '人民币',
        value: 'CNY',
    },
    {
        label: '美元',
        value: 'USD',
    },
]

export const searchList = [
    "act",
    "ada",
    "adx",
    "ae",
    "aion",
    "amp",
    "ant",
    "ardr",
    "ark",
    "atm",
    "bat",
    "bay",
    "bcc",
    "bch",
    "bcn",
    "bdl",
    "bela",
    "blcn",
    "blk",
    "block",
    "bnb",
    "bnt",
    "bq",
    "bqx",
    "btc",
    "btcd",
    "btcz",
    "btg",
    "btm",
    "bts",
    "btx",
    "burst",
    "clam",
    "cnx",
    "cny",
    "cvc",
    "dash",
    "data",
    "dbc",
    "dcn",
    "dcr",
    "dent",
    "dgb",
    "dgd",
    "doge",
    "drgn",
    "edg",
    "edoge",
    "elf",
    "emc",
    "emc2",
    "eng",
    "eos",
    "etc",
    "eth",
    "ethos",
    "etn",
    "etp",
    "eur",
    "evx",
    "exmo",
    "exp",
    "fair",
    "fct",
    "fil",
    "fldc",
    "flo",
    "fun",
    "game",
    "gas",
    "gbp",
    "gbx",
    "gbyte",
    "gno",
    "gnt",
    "grc",
    "grs",
    "gup",
    "gxs",
    "hsr",
    "huc",
    "hush",
    "icn",
    "icx",
    "jpy",
    "kcs",
    "kin",
    "kmd",
    "knc",
    "krb",
    "lbc",
    "link",
    "lkk",
    "lrc",
    "lsk",
    "ltc",
    "maid",
    "mana",
    "mcap",
    "mco",
    "miota",
    "mln",
    "mnx",
    "mona",
    "mtl",
    "music",
    "nav",
    "nebl",
    "neo",
    "neos",
    "nlc2",
    "nlg",
    "nmc",
    "nxs",
    "nxt",
    "omg",
    "omni",
    "part",
    "pasl",
    "pay",
    "pink",
    "pivx",
    "poe",
    "pot",
    "powr",
    "ppc",
    "ppt",
    "pura",
    "qash",
    "qiwi",
    "qsp",
    "qtum",
    "rads",
    "rcn",
    "rdd",
    "rdn",
    "rep",
    "req",
    "rhoc",
    "ric",
    "rlc",
    "rub",
    "salt",
    "san",
    "sbd",
    "sberbank",
    "sc",
    "sky",
    "smart",
    "sngls",
    "snt",
    "start",
    "steem",
    "storj",
    "storm",
    "strat",
    "sub",
    "taas",
    "tkn",
    "trx",
    "tzc",
    "ubq",
    "usd",
    "usdt",
    "ven",
    "veri",
    "via",
    "vivo",
    "vrc",
    "vtc",
    "waves",
    "wax",
    "wtc",
    "xbc",
    "xcp",
    "xdn",
    "xem",
    "xlm",
    "xmr",
    "xpm",
    "xrb",
    "xrp",
    "xtz",
    "xuc",
    "xvc",
    "xvg",
    "xzc",
    "zcl",
    "zec",
    "zen",
    "zrx"
  ]
